import './css/style.css';
import './js/app';
import './img/visa.png';
import './img/american_express.png';
import './img/jcb.png';
import './img/mastercard.png';
import './img/discover.png';
import './img/dinersclub.png';
import './img/mir.png';
